const RETRIEVE_TUTORIALS = "RETRIEVE_TUTORIALS";
const RETRIEVE_TUTORIAL_BY_ID = "RETRIEVE_TUTORIAL_BY_ID";
const RETRIEVE_TUTORIAL_BY_TITLE = "RETRIEVE_TUTORIAL_BY_TITLE";
const RETRIEVE_TUTORIAL_BY_STATUS = "RETRIEVE_TUTORIAL_BY_STATUS";
const CREATE_TUTORIAL = "CREATE_TUTORIAL";
const UPDATE_TUTORIAL = "UPDATE_TUTORIAL";
const DELETE_TUTORIAL = "DELETE_TUTORIAL";
const DELETE_ALL_TUTORIALS = "DELETE_ALL_TUTORIALS";
const RESET_TUTORIAL="RESET_TUTORIAL";

export {
    RETRIEVE_TUTORIALS,
    RETRIEVE_TUTORIAL_BY_ID,
    RETRIEVE_TUTORIAL_BY_TITLE,
    RETRIEVE_TUTORIAL_BY_STATUS,
    CREATE_TUTORIAL,
    UPDATE_TUTORIAL,
    DELETE_TUTORIAL,
    DELETE_ALL_TUTORIALS,
    RESET_TUTORIAL
}